### ISSUE TITLE
Handle conversion of data to csv format

### ISSUE THREAD

**Issue by BrendenMarks** [cs481-ekh/f22-fires-wild#105]
We have QSPs in the backend api from #106. Now we need to send it as CSV on a new api endpoint

Acceptance Criteria:

- [x] New endpoint like the one made in #106, but serializes to CSV for all parameters
   - Note: first line of CSV is always column names

**Comment by David5886** [comment]
I spent a couple hours researching, and a couple of hours implementing this new back-end function that allows us to generate a csv from a database query. I used the following sources to help me build my implementation. The only issues I ran into was having no data get imported into the database, then the column names being inserted instead of the actual database. The final issue I was getting was the initial first line getting filled with data as well in a kind of json format. But in this current implementation it is working at intended. 

https://stackoverflow.com/a/56947182
https://docs.djangoproject.com/en/4.1/howto/outputting-csv/
