### ISSUE TITLE
Automate my-sql container population

### ISSUE THREAD

**Issue by samwise-311** [cs481-ekh/f22-fires-wild#167]
Setup/research an automated process of populating the my-sql container with data. This will allow for automated tests to be run in CI

## Definition of Done
- [ ] A CI compatible automation of a my-sql sign in and population of container with valid data.

## Tasks
- [x] #169 
- [x] #171

**Comment by collins-benjaminw** [comment]
doc'ing my work here:
This story was very sneaky with its problems. Scripting the sql imports was actually very simple; I had to use `docker exec` to throw the default user and password in, and `<<<` to push the query to STDIN. This allowed me to do whatever I wanted on the sql container in the script, which was very cool.

The problems arose with trying to get cypress tests to succeed in github actions. I ran into an immediate `Error: Socket hang up` which I thought to be a network problem, and spent a decent amount of time trying to troubleshoot it. I became frustrated that the github actions env was different than my local. It was just enough of a difference of some degree that I couldn't really research this problem and spent hours "throwing things against the wall" (not literally) to see what would stick. In the process I learned a ton about github actions, docker, docker-compose, docker networks, etc. You can see my frustration and learning play out in the pull request #172.
After a good night's rest, I was able to deduce that the mysql container was not utilizing the 3308 port internally (which it doesn't have to in its own container) in the github actions, where it had been coaxed to in my local container. I have no idea why. I updated config to match the 3308:3306 that I was seeing, and everything magically worked. I also added a fail after 50 seconds to the "waiting for database" loop so that we won't run the actions indefinetly.
